networks:
  forumNetwork:
    driver: bridge
services:
  database:
    image: mariadb:10.11-rc
    environment:
      MARIADB_ROOT_PASSWORD_HASH: "*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19"
      MARIADB_DATABASE: "forum"
      MARIADB_USER: "forumApp"
      MARIADB_PASSWORD_HASH: "*0A7A4E64514FC3F69614759689B0E6D5F9C286CD"
    ports:
      - "3307:3306"
    volumes:
      - ~/mariaDbForum:/var/lib/mysql
    networks:
      - forumNetwork
  web:
    build: .
    ports:
      - "8000:8080"
    networks:
      - forumNetwork
    depends_on:
      - database
    restart: on-failure